
spring.application.name=FoodOrderingSystem
server.port=8090

app.jwt.secret=7f9d2c4a8e6b1f0c9a3d5e7f2b8c4d6e9f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5
app.jwt.expiration-ms=86400000

#DB COnfig

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.url=jdbc:mysql://localhost:3306/food_ordering_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

# JPA / Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SQL initialization - load schema.sql and data.sql on startup
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
